version: "3.3"

services:
  drupal:
    build: .
    environment:
#      - DEBUG_MODE=no
#      - DEBUG_MODE=connect_back
      - DEBUG_MODE=docker_host
    volumes:
      - site-data:/data
      - ./app:/app
    ports:
      - 48080:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=changeme
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  site-data:
  mysql-data: